### PR TITLE
[chaos] Configure layout paddings 

### LINKED ISSUE #57: Use right spacing in header
## Description

image

image

### PR DESCRIPTION
**Pull request by andreifilip123**
### What does it fix?
This fixes #57 and #53 

This PR:
* removes the `hacky` spacing in the header by using the builtin flex property `justify-content: 'space-between';`
* adds the [`<Container>` component](https://material-ui.com/components/container/) to the header and footer to use the same maxWidth.
* fixes some paddings in footer (both desktop and mobile)

### CODE REVIEW

**Review by radubuciuceanu — CHANGES_REQUESTED** [review]
Header requirements are still not met. Should we consider making them also?

image

**Comment by andreifilip123** [comment]
Actually, to me, the header and the footer seem to be fixed. The only thing that's left to be fixed is the main content of the page. That needs to be capped in a `<Container>` but I left that out of this PR.

**Comment by andreifilip123** [comment]
Wrapped the page content in a `<Container>` as well.

**Review by radubuciuceanu — CHANGES_REQUESTED** [review]
Header items are no more vertically centered. Should we consider changing that one also?

image

**Review by radubuciuceanu — CHANGES_REQUESTED** [review]
Let's not change the whole page paddings. It's ugly to have them full widthted on md+ screens. The visual aria of the user should be small. Let's better make the header and the footer to follow the page's paddings.

So instead of doing this:
image

Let's add the right paddings here:
image

**Comment by radubuciuceanu** [comment]
Closing this PR in flavor of #75 and #74

**Pull request closed without merging**
